<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-02-05 at 07:40:12.
 */
class htmlElementRetouchTest extends PHPUnit_Framework_TestCase {

    /**
     * @var htmlElementRetouch
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new htmlElementRetouch;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers htmlElementRetouch::exec
     * @todo   Implement testExec().
     */
    public function testExec() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers htmlElementRetouch::_createSelector
     */
    public function test_createSelector() {
        // 要素一つ
        $this->assertEquals(
                ["//span"],
                $this->object->_createSelector("<span>aaaa</span>")
            );

        // クラスを付ける
        $this->assertEquals(
                ['//span[@name="robots"][@content="index,follow"]'],
                $this->object->_createSelector('<span name="robots" content="index,follow">aaaa</span>')
            );
        
        // 並列要素
        $this->assertEquals(
                ["//li", "//li", "//li"],
                $this->object->_createSelector("<li>aaa</li><li>bbb</li><li>ccc</li>")
            );
        
        // 親子
        $this->assertEquals(
                ["//ul//li", "//ul//li", "//ul//li"],
                $this->object->_createSelector("<ul><li>aaa</li><li>bbb</li><li>ccc</li></ul>")
            );
    }

}
