<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-02-05 at 07:40:12.
 */
class htmlElementRetouchTest extends PHPUnit_Framework_TestCase {

    /**
     * @var htmlElementRetouch
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new htmlElementRetouch;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers htmlElementRetouch::exec
     * @todo   Implement testExec().
     */
    public function testExec() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );

    }

    /**
     * @covers htmlElementRetouch::_createSelector
     * @todo   Implement test_createSelector().
     */
    public function test_createSelector() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers htmlElementRetouch::_getNodesInfo
     * @todo   Implement test_getNodesInfo().
     */
    public function test_getNodesInfo() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
